#!/bin/bash

echo "=========================================="
echo "Browser Cache Clearing Instructions"
echo "=========================================="
echo ""
echo "The frontend dev server has been restarted with a fresh build."
echo "Server is running at: http://localhost:5173/"
echo ""
echo "To see the updated User Personas report, please:"
echo ""
echo "1. CLOSE your browser completely (all windows)"
echo "2. REOPEN your browser"
echo "3. Navigate to: http://localhost:5173/"
echo "4. Go to User Personas report"
echo ""
echo "OR use Incognito/Private mode:"
echo "- Chrome: Cmd+Shift+N"
echo "- Firefox: Cmd+Shift+P"
echo "- Safari: Cmd+Shift+N"
echo ""
echo "Expected changes:"
echo "✓ Single consolidated summary panel (not 3 separate cards)"
echo "✓ Professional gradient styling"
echo "✓ Hover effects on summary stats"
echo "✓ Sticky table header"
echo ""
echo "=========================================="
